---
title: "Marília Melo Favalesso"
author: Marília Melo Favalesso
date: "`r Sys.Date()`"
output:
  pagedown::html_resume:
    # set it to true for a self-contained HTML page but it'll take longer to render
    self_contained: true
    css: [ 'dd_cv.css', 'custom.css','resume']
---
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

Aside
================================================================================

<i class='fas fa-download'></i> [Download this CV in PDF](cv.pdf)

Contact {#contact}
--------------------------------------------------------------------------------
- `r fontawesome::fa("link")` [www.mmfava.com](www.mmfava.com)
- `r fontawesome::fa("envelope")` biologist.mmf@gmail.com
- `r fontawesome::fa("twitter")` [mmfbee](https://twitter.com/mmfbee)
- `r fontawesome::fa("github")` [github/mmfava](https://github.com/mmfava)

Themes {#contact}
--------------------------------------------------------------------------------
- `r fontawesome::fa("table")` `Biostatistics`
- `r fontawesome::fa("laptop-code")` `Programming in R / Python`
- `r fontawesome::fa("search")` `Ecoepidemiology`
- `r fontawesome::fa("pagelines")` `Conservation`
- `r fontawesome::fa("bug")` `Entomology`


Skills {#skills}
--------------------------------------------------------------------------------
- `r fontawesome::fa("r-project")` [`R`](https://www.r-project.org/)
- `r fontawesome::fa("markdown")` [`markdown`](https://daringfireball.net/projects/markdown/)
- `r fontawesome::fa("code-branch")` [`git`](https://git-scm.com/)
- `r fontawesome::fa("python")` [`python (basic)`](https://www.python.org/)
- `r fontawesome::fa("quora")` [`QGIS`](https://qgis.org/en/site/)

Languages {#skills}
--------------------------------------------------------------------------------
- Portuguese (Native speaker)
- English (Intermediary)
- Spanish (Advanced)

Disclaimer {#disclaimer}
------------------------------------
CV by [**pagedown**](https://github.com/rstudio/pagedown) R package.  
Code available on `r fontawesome::fa("github")` [GitHub](https://github.com/mmfava/site).  
Last updated on `r Sys.Date()`.

Main
================================================================================

Marília Melo Favalesso {#title}
--------------------------------------------------------------------------------

Education {data-icon=graduation-cap}
--------------------------------------------------------------------------------

### Universidad de Buenos Aires

[Doctoral Student in Ecology, Genetics and Evolution](http://www.ege.fcen.uba.ar/)

Buenos Aires capital, Argentina

2018 - Present

**Provisional thesis title**: Ecoepidemiological studies of *Lonomia achelous* and *Lonomia obliqua* (Saturniidae: Hemileucinae) in South America.

**Advisor**: PhD. Maria elisa Peichoto and PhD. Ana Tereza Bittencourt Guimarães

### Universidade Estadual do Oeste do Paraná (UNIOESTE)

[Master in environmental Sciences](https://www5.unioeste.br/portalunioeste/pos/pprn)

Cascavel, PR, Brazil

2016 - 2018

**Thesis**: Ecological conditions and prediction of available areas for Lonomia obliqua walker 1855 in Brazil ([UNIOESTE Libraries](http://tede.unioeste.br/handle/tede/3961))  
**Advisor**: PhD. Ana Tereza Bittencourt Guimarães

### Universidade Federal do Paraná (UFPR)

[Bachelor in Biological Sciences](http://www.palotina.ufpr.br/portal/ciencias-biologicas/)

Palotina, PR, Brazil

2010 - 2014

**Thesis**: Bees and wasps (Hymenoptera) as ecological indicators in a forest restoration area.  
**Advisor**: PhD. Rodrigo Barbosa Gonçalves


Complementary Education {data-icon=book}
--------------------------------------------------------------------------------
### Generalized linear mixed model

Universidad de Buenos Aires, UBA (remote)

Argentina

2021

::: concise
- 40 h 
:::


### Quantitative remote sensing applied to environmental problems

Universidad Nacional de General San Martin, UNSAM (remote)

Argentina

2020

::: concise
- 64 h 
:::

### Introduction to Bayesian Statistical Methods in Ecology 

Universidad de Buenos Aires (UBA)

Buenos Aires capital, Argentina

2019

::: concise
- 60 h 
:::

### Epidemiology

Universidade Estadual do Oeste do Paraná (UNIOESTE)

Foz do Iguaçu, PR, Brazil

2019

::: concise
- 60 h
:::

### Time series modeling

Universidad de Buenos Aires (UBA)

Buenos Aires capital, Argentina

2019

::: concise
- 60 h
:::

### Advanced models in health and environment

Universidad de Buenos Aires (UBA)

Buenos Aires capital, Argentina

2018

::: concise
- 60 h
:::

### School of Advanced Training in Panoramic Epidemiology

Instituto Gulich

Córdoba, Argentina

2018

::: concise
- 84 h
:::

### Biotoxinology

Universidade da Integração Latino-Americana (UNILA)

Foz do Iguaçu, PR, Brazil

2018

::: concise
- 45 h
:::

### Ecological niche modeling: theory and practice

Universidade Estadual Paulista (UNESP)

Rio Claro, SP, Brazil

2017

::: concise
- 60 h
:::

### Environmental quality and natural resource management

Universidade Estadual do Oeste do Paraná (UNIOESTE)

Cascavel, PR, Brazil

2016

::: concise
- 60 h
:::

### Multivariate analysis

Universidade Estadual do Oeste do Paraná (UNIOESTE)

Cascavel, PR, Brazil

2016

::: concise
- 60 h
:::

### Special topics in methodology and scientific writing

Universidade Estadual do Oeste do Paraná (UNIOESTE)

Cascavel, PR, Brazil

2016

::: concise
- 60 h
:::

### Basic level statistics

Universidade Estadual do Oeste do Paraná (UNIOESTE)

Cascavel, PR, Brazil

2016

::: concise
- 60 h
:::

### Numerical ecology

Universidade Estadual do Oeste do Paraná (UNIOESTE)

Cascavel, PR, Brazil

2015

::: concise
- 60 h
:::

### Theoretical ecology

Universidade Estadual do Oeste do Paraná (UNIOESTE)

Cascavel, PR, Brazil

2015

::: concise
- 60 h
:::

### Short course in *XII Summer Course in Entomology*

Universidade de São Paulo (USP)

Ribeirão Preto, SP, Brazil

2014

::: concise
- 90 h
:::

### Short Course in *Forensic Entomology*

RENOVA cursos

Cascavel, PR, Brazil

2012

::: concise
- 8 h
:::

### Short Course in DNA Forensic Analysis

RENOVA cursos

Cascavel, PR, Brazil

2012

::: concise
- 8 h
:::


Professional Experience {data-icon=suitcase}
--------------------------------------------------------------------------------

### Biostatistics consultancy and advice

[Qual é a sua pergunta?](https://qualesuapergunta.wixsite.com/consultoria)

Cascavel, PR, Brazil

2015 - 2016

::: concise
- Univariate statistical analysis
- Multivariate statistical analysis
- Non-parametric statistical analysis
- Ecological analyzes
- R courses
- Latex course integrated with R
- Mendeley course
:::

Teaching Experience {data-icon=chalkboard-teacher}
--------------------------------------------------------------------------------
### Eco-epidemiological tools for surveillance of accidents with venomous animals

Taught class - 
UNILA

Foz do Iguaçu, PR, Brazil

2021

::: concise
- 5 h 
- [link](https://www.mmfava.com/posts/2021-05-11-ferramentas-ecoepidemio/)
:::

### Introduction to Git and GitHub in RStudio

Short course instructor -
R-Ladies Fortaleza

Fortaleza, CE, Brazil

2020

::: concise
- 4 h 
- [link](https://www.mmfava.com/posts/2021-03-24-git-e-github-com-o-rstudio/)
:::

### Species distribution models: an introduction.

Short course instructor -
R-Ladies BH

Belo Horizonte, MG, Brazil

2020

::: concise
- 1 h 
- [link](https://www.mmfava.com/posts/2021-04-01-introduo-a-modelagem-de-distribuio-de-espcies-com-exemplo-no-r/)
:::

### Descriptive statistics

Short course instructor 
Grupo de Estudos em Ciência de Dados (GECD)

Foz do Iguaçu, PR, Brazil

2019

::: concise
- 4 h 
- [material](https://github.com/gecdfoz/GECD/tree/master/Cursos/2019.1/02-0709)
:::

### Introduction to R Language

Short course instructor 
Grupo de Estudos em Ciência de Dados (GECD)

Foz do Iguaçu, PR, Brazil

2019

::: concise
- 4 h 
- [material](https://github.com/gecdfoz/GECD/tree/master/Cursos/2019.1/04-1210)
:::

### Ecological Niche Modeling (ENM) and Species Distribution (SDM) in R

Short course instructor 
*XXVI Semana Acadêmica de Ciências Biológicas*
UNIOESTE

Cascavel, PR, Brazil

2017

::: concise
- 4 h 
- [material]()
:::

### Numerical ecology in R

Short course instructor  
*XXV Semana Acadêmica de Ciências Biológicas*
UNIOESTE

Cascavel, PR, Brazil

2016

::: concise
- 4 h 
- [material](https://www.mmfava.com/posts/2021-05-13-mini-curso-de-ecologia-numerica/)
:::


### Introduction to R Language

Short course instructor  
Universidade Federal do Paraná (UFPR)

Palotina, PR, Brazil

2016

::: concise
- 24 h
- [material]()
:::



Publications {data-icon=file}
--------------------------------------------------------------------------------
### 7. *Lonomia* envenomation in Brazil: an epidemiological overview for the period 2007-2018.

*Transactions of The Royal Society of Tropical Medicine and Hygiene* 115: 9-19

N/A

2021

DOI: [10.1093/trstmh/traa051](https://academic.oup.com/trstmh/article-abstract/115/1/9/5908316?redirectedFrom=fulltext)  

<u>**Favalesso MM**</u>, Cuervo PF, Casafús M, Guimarães ATB and Peichoto ME

::: aside
**Citations**  
[Google Scholar](https://scholar.google.com.br/citations?user=fJuPSpAAAAAJ&hl=pt-BR&oi=ao)  
:::

### 6. Report of predatory events in *Lonomia* sp. (Saturniidae: Hemileucinae).

*Oecologia australis* 24(1): 235-241

N/A

2020

DOI: [oeco.2020.2401.23](https://doi.org/10.4257/oeco.2020.2401.23)  

<u>**Favalesso MM**</u>, Chiyo L, Casafús M, Guimarães ATB and Peichoto ME

### 5. Potential distribution and ecological conditions of *Lonomia obliqua* Walker 1855 (Saturniidae: Hemileucinae) in Brazil

*Acta tropica* 192: 158-164

N/A

2019

DOI: [10.1016/j.actatropica.2019.01.016](https://doi.org/10.1016/j.actatropica.2019.01.016)  
<u>**Favalesso MM**</u>, Lorini LM, Peichoto ME and Guimarães ATB


### 4. Recorriendo Misiones para el registro ecoepidemiológico de la oruga venenosa *Lonomia* spp. (Saturniidae: Hemileucinae)

*Boletín de la Sociedad Entomológica Argentina* 30: 4-7

N/A

2019

Full text: [BSEA](https://ri.conicet.gov.ar/bitstream/handle/11336/107348/CONICET_Digital_Nro.9ae8f9e9-e361-4e98-a9a8-36286ac3cc6c_B.pdf?sequence=5&isAllowed=y)

Casafús M, <u>**Favalesso MM**</u>, Guimarães ATB and Peichoto ME


### 3. Construction of meanings in practical lessons of biology laboratory: an evaluation by quasi-experimental design

*Revista brasileira de ensino de ciência e tecnologia* 12(3): 78-93

N/A

2019

DOI: [10.3895/rbect.v12n3.7608](https://periodicos.utfpr.edu.br/rbect/article/view/7608)

<u>**Favalesso MM**</u>, Oliveira JB, Klüber TE and Guimarães ATB


### 2. Effects of trichlorfon used in the treatment of parasitosis on biological metrics of farmed *Ctenopharingodon idella* (Valenciennes, 1844)

*Archives of Veterinary Science* 24(2): 61-72

N/A

2019

DOI: [10.5380/avs.v24i2.57734]( http://dx.doi.org/10.5380/avs.v24i2.57734) 

Guimarães ATB, Sobjak TM, <u>**Favalesso MM**</u> and Boeger WAP


### 1. Bees and wasps (Hymenoptera) as ecological indicators in a forest restoration area 

*Oecologia australis* 21(4): 396-406

N/A

2017

DOI: [10.4257/oeco.2017.2104.04](https://doi.org/10.4257/oeco.2017.2104.04)

<u>**Favalesso MM**</u> and Gonçalves RB


Scientific articles in press {data-icon=file}
--------------------------------------------------------------------------------
### 2. A hidden deadly venomous insect: first eco-epidemiological assessment and risk mapping of lonomism in Argentina

*Plos One NDTS* 

N/A

2021

Casafús MG, <u>**Favalesso MM**</u>, Gritti MA, Coronel JM, Guimarães ATB and Peichoto ME

### 1. Land use as an effect factor on the occurrence of chromosomal diseases in Brazil

*International Journal of Molecular Epidemiology and Genetics*

N/A

2021

Cochak MR, <u>**Favalesso MM**</u>, Brancalhão RMC, Guimarães ATB and Ribeiro LFC

Scientific articles in development {data-icon=file}
--------------------------------------------------------------------------------
### Revealing the landscape and climate as key factors that influence lonomic accidents in southern Brazil

Data analysis process

N/A

2021

<u>**Favalesso MM**</u>, Cuervo P, Guimarães ATB and Peichoto ME

### Perfil de resistencia a antimicrobianos en microorganismos productores de carbapenemasas aislados en un hospital de Corrientes (Argentina)

In process of writing 

N/A

2021

Gritti AG, <u>**Favalesso MM**</u>, Peichoto ME and Aguirre LGGC

### Bee sting notifications in São Paulo (Brazil) between 2007 and 2018

Submitted for consideration in [EcoHealth journal](https://www.springer.com/journal/10393)

N/A

2021

<u>**Favalesso MM**</u>, Oliveira PS, Burgos EF, Frazeto IB and Souza R


Oral communications {data-icon=volume-up}
--------------------------------------------------------------------------------

### [A importâcia dos dados na profissão do biólogo](https://www.dropbox.com/s/qx80sg35ovji3e6/VI%20congresso%20int%20de%20vet%20e%20biologia%20-%20importancia%20dos%20dados%20na%20prof%20do%20biologo.jpeg?dl=0)

VI Congresso Internacional de Medicina Veterinária e Ciências Biológicas

Foz do Iguaçu, PR, Brazil

2019


### [Caracterización clínica y epidemiológica de los accidentes con *Lonomia* en Misiones (Argentina)](https://www.dropbox.com/s/qvxyrqw081ur3lc/AP-O%20II%20Simposio%20de%20Bioci%C3%AAncias%202019.pdf?dl=0)

II Simpósio Latino-Americano de Biociências

Foz do Iguaçu, PR, Brazil

2019

### [Cuidado onde toca: panorama sobre o lonomismo no Brasil](https://www.dropbox.com/s/mlz7e3g1c10e929/S%20Semin%C3%A1rios%20em%20Bioci%C3%AAncia%202019.pdf?dl=0)

Seminários de Pesquisa em Biociência - UNILA

Foz do Iguaçu, PR, Brazil

2019

### [Distribuição potencial e aspectos ecológicos da taturana venenosa *Lonomia obliqua* walker 1855 no Brasil](https://www.dropbox.com/s/22c9km7g0xcmh56/AP-O%20I%20Simp%C3%B3sio%20de%20Bioci%C3%AAncias%202018.pdf?dl=0)

I Simpósio Latino-Americano de Biociências

Foz do Iguaçu, PR, Brazil

2018

### [Modelagem de nicho ecológico por entropia máxima](https://www.dropbox.com/s/pidmkakajdhs04d/P%20Semin%C3%A1rios%20em%20Conserva%C3%A7%C3%A3o%20e%20Menejo%20de%20Recursos%20Naturais.pdf?dl=0)

Seminários em Conservação e Manejo de Recursos Naturais

Cascavel, PR, Brazil 

2017

### [Estrutura da rede de interação entre abelhas e angiospermas nativas de floresta estacional semidecidual (Parque Estadual de São Camilo, Palotina, Paraná)](https://www.dropbox.com/s/ya0gmvbboaw0h3k/AP-O%2022%20EVINCI%207%20EINTI%202014.pdf?dl=0)

22º EVINCI/7º EINTI

Palotina, PR, Brazil

2014

### [Conceitos básicos de evolução](https://www.dropbox.com/s/x5zt7u3znbg8wxo/P%20GEB%202013.pdf?dl=0)

Grupo de Estudos em Bioética (GEB) - UFPR

Palotina, PR, Brazil

2013

### [Estudo preliminar da fauna cadavérica no município de Palotina, Paraná - sucessão entomológica](https://www.dropbox.com/s/gu4oo991p19jimy/P%20GEP%202012.pdf?dl=0)

20º EVINCI/5º EINTI

Palotina, PR, Brazil

2012

### [A relevância da decomposição cadavérica]()

Grupo de Estudos em Pesquisas Forense (GEP Forense) - UFPR

Palotina, PR, Brazil

2012


Publications from events {data-icon=book-open}
--------------------------------------------------------------------------------

### [Distribución potencial de los principales hospedadores (*Biomphalaria* spp., Mollusca, Gasteropoda: Planorbidae) de la esquistosomiasis en Paraguay](https://drive.google.com/file/d/1Gprrl4s8FLMHN0aKNWAeittelGemLqPS/view)

Primer Congreso Paraguayo de Zoología

Asunción, Paraguay

2019

Casaccia PS, Burgos EF, <u>**Favalesso MM**</u>, Rios SD, Mereles MF, Arias AR

### [Caracterización clínica y epidemiológica de los accidentes con *Lonomia* en Misiones (Argentina)](https://github.com/mmfava/Simposio_Latinoamericano_Biociencias_II)

II Simpósio Latino-Americano de Biociências

Foz do Iguaçu, PR, Brazil

2019

<u>**Favalesso MM**</u>, Couto EM, Casafús M, Gritti MA, Guimarães ATB and Peichoto ME


### [Prioridades para prevenir el establecimiento y dispersión del lirio amarillo en regiones susceptibles](https://www.dropbox.com/s/g24d3qxcbc74spm/2019%20GERVAZONI%20et%20al.%20-%20VI%20Congreso%20Nacional%20de%20Conservaci%C3%B3n%20de%20la%20Biodiversidad.pdf?dl=0)

VI Congreso Nacional de Conservación de la Biodiversidad 

Argentina

2019

Gervazoni P, <u>**Favalesso MM**</u>, Franceschini C, Fuentes Rodriguez D, Sosa A, Coetzee J and Hill M


### [Lonomismo no Brasil: análise epidemiológica dos acidentes causados pela taturana venenosa no período de 2007 e 2018](https://733a1b04-0b5d-4c37-aa16-b097f5a5362b.filesusr.com/ugd/d485a1_c0184a5c48e24cfc9c3fda7aaec28546.pdf)

IX Simpósio de Zoonoses com Interesse em Saúde Pública

Palotina, PR, Brazil

2019

<u>**Favalesso MM**</u>, Casafús M, Guimarães ATB and Peichoto ME

### [Acidentes com abelhas do mel no estado de São Paulo](https://733a1b04-0b5d-4c37-aa16-b097f5a5362b.filesusr.com/ugd/d485a1_c0184a5c48e24cfc9c3fda7aaec28546.pdf)

IX Simpósio de Zoonoses com Interesse em Saúde Pública

Palotina, PR, Brazil

2019

<u>**Favalesso MM**</u>, Oliveira PS and Burgos E

### [Abordagem clínico-epidemiológica de loxoscelismo na região de Foz do Iguaçu-PR](https://733a1b04-0b5d-4c37-aa16-b097f5a5362b.filesusr.com/ugd/d485a1_c0184a5c48e24cfc9c3fda7aaec28546.pdf)

IX Simpósio de Zoonoses com Interesse em Saúde Pública

Palotina, PR, Brazil

2019

Lescano ME, Ripoli MC, Oliveira WF, <u>**Favalesso MM**</u>, Peichoto ME and Tavares FL

### [Distribuição potencial e aspectos ecológicos da taturana venenosa *Lonomia obliqua* Walker 1855 no Brasil](https://docs.wixstatic.com/ugd/7d7870_c408dd67d3674203a454221959af49eb.pdf)

I Simpósio Latino-Americano de Biociências

Foz do Iguaçu, PR, Brazil

2019

<u>**Favalesso MM**</u>, Casafús MG, Lorini LM, Guimarães ATB and Peichoto ME

### [Contribuição ao conhecimento sobre a distribuição de acidentes e plantas hospedeiras da taturana venenosa *Lonomia* spp. (Saturniidae: Hemileucinae) na província de Misiones – Argentina](https://docs.wixstatic.com/ugd/7d7870_a48dd72cbc03499fa1da5443991a275e.pdf)

I Simpósio Latino-Americano de Biociências

Foz do Iguaçu, PR, Brazil

2019

Casafus M, <u>**Favalesso MM**</u>, Couto E, Gatti F, Guimarães ATB and Peichoto ME

### [Revealing land-use change as a key factor influencing the incidence of envenomation by *Lonomia* sp. in southern Brazil](https://docs.wixstatic.com/ugd/cccb67_03de2b15082949418b706d8db308d59b.pdf)

3th International Symposium of Ecology (SINECO)

Foz do Iguaçu, PR, Brazil

2019

<u>**Favalesso MM**</u>, Burgos E, Peichoto ME and Guimaraes ATB


### [Predict areas of occurrence of *Lonomia obliqua* Walker 1855 (Saturniidae, Hemileucinae) in the province of Misiones, Argentina](https://www.researchgate.net/publication/321781213_PREDICT_AREAS_OF_OCCURRENCE_OF_Lonomia_obliqua_WALKER_1855_SATURNIIDAE_HEMILEUCINAE_IN_THE_PROVINCE_OF_MISIONES_ARGENTINA)

Reunión conjunta de sociedades de Biociências

Buenos Aires capital, Argentina

2017

<u>**Favalesso MM**</u>, Casafus MG, Guimaraes ATB and Peichoto ME 

### [Predição de áreas climaticamente adequáveis para *Automeris naranja* Schaus, 1898 (Lepidoptera, Saturniidae, Hemileucinae) no sul do Brasil](https://midas.unioeste.br/sgev/eventos/sabUnioeste2017/anais)

XXVI Semana Acadêmica de Ciências Biológicas da UNIOESTE

Cascavel, PR, Brazil

2017

Bastos EFM, <u>**Favalesso MM**</u>, and Guimaraes ATB

### [Qual é sua pergunta?](https://www5.unioeste.br/eventos/seu/anais/XVII_SEU_Anais.pdf)

XVII Seminário de Extensão da UNIOESTE

Cascavel, PR, Brazil

2017

Guimarães ATB, Paoletti M, Cargnelutti-Júnior JC, <u>**Favalesso MM**</u>, Dal'Canton LE and Sobjak T

### [Comparação dos parâmetros abióticos d'água entre três pontos na bacia do rio Cascavel](https://www.dropbox.com/s/3mbwv58z1pv08im/2016%20MEDEIROS%20et%20al.%20-%20XXV%20Semana%20academica%20de%20biologia.pdf?dl=0)

XXV Semana Acadêmica de Biologia

Cascavel, PR, Brazil

2016

Medeiros G, <u>**Favalesso MM**</u>, Nabeshima CA, Favaretto CC and Bueno NC

### [Sericina da seda exerce efeito protetor sobre a morfologia de espermatozoides de camundongos C57BL/6 alimentados com dieta High Fat](https://www.researchgate.net/publication/321781524_SERICINA_DA_SEDA_EXERCE_EFEITO_PROTETOR_SOBRE_A_MORFOLOGIA_DE_ESPERMATOZOIDES_DE_CAMUNDONGOS_C57BL6_ALIMENTADOS_COM_DIETA_HIGH_FAT)

XV Congresso Brasileiro de Biomedicina & III Congresso Internacional de Biomedicina

Bento Gonçalves, RS, Brazil

2016

Scarton SRS, <u>**Favalesso MM**</u>, Kunz RI, Bracalhão RC, Guimarães ATB and BEU CCL

### [Análise bibliográfica sobre o uso de peixes como bioindicadores da integridade biótica dos ecossistemas aquáticos brasileiros: Ambientes de amostragem](https://www.researchgate.net/publication/321781396_ANALISE_BIBLIOGRAFICA_SOBRE_O_USO_DE_PEIXES_COMO_BIOINDICADORES_DA_INTEGRIDADE_BIOTICA_DOS_ECOSSISTEMAS_AQUATICOS_BRASILEIROS_AMBIENTES_DE_AMOSTRAGEM)

V Seminário sobre Estudos Limnológicos em Clima Subtropical (V SELCS)

Curitiba, PR, Brazil

2016

Berlatto AF, Bogoni RF, Ticiani D, Eichelberger AC, Malagi I, Medeiros G, <u>**Favalesso MM**</u>, Delariva RL

### [Abelhas que coletam o pólen por vibração em flores de Solanaceae no Parque Estadual de São Camilo, Palotina, Paraná](http://www.seb.org.br/admin/files/book/book_nTi2y3ZTHwRm.pdf)

XXV Congresso de Entomologia

Goiânia, GO, Brazil

2014

<u>**Favalesso MM**</u>, Gonçalves RB

### [Estrutura da rede de interação entre abelhas e angiospermas nativas de Floresta Estacional Semidecidual (Parque Estadual de São Camilo, Palotina, Paraná)](http://www.siepe.ufpr.br/2014/evinci/0162.html)

22º EVINCI e 6ª SIEPE

Palotina, PR, Brazil

2014

### [Estudo da fauna cadavérica no município de Palotina, Paraná - Descrição das características da decomposição cadavérica](https://revistas.ufpr.br/veterinary/article/view/33866/21150)

XVI ENAPAVE - Archives of Veterinary Science, v. 18, p. 349-351

Curitiba, PR, Brazil

2013

Tostes RA, Caron E, Cestari FK, <u>**Favalesso MM**</u> and Silva NL

### [Estudo da Fauna Cadavérica no Município de Palotina, Paraná - Descrição das Características da Decomposição Cadavérica](https://www.dropbox.com/s/y7ispjszy1av52o/2013%20CESTARI%20et%20al.%20-%20MEDVEP.pdf?dl=0)

MedVep de Especialidades Veterinárias

Bento Gonçalves, RS, Brazil

2013

Cestari FK, Silva NL, Tostes RA, <u>**Favalesso MM**</u> and Caron E

### [Estudo da Fauna Cadavérica no Município de Palotina, Paraná – Alterações Biogeoclimáticas e Sua Relação com a Decomposição Cadavérica](https://www.dropbox.com/s/edi11cldg3c7eek/2013%20TOSTES%20et%20al.%20-%20MEDVEP.pdf?dl=0)

MedVep de Especialidades Veterinárias

Bento Gonçalves, RS, Brazil

2013

Tostes RA, Cestari FK, Silva NL, <u>**Favalesso MM**</u> and Caron E

### [A influência de um grupo de estudos sobre bioética na Universidade Federal do Paraná, Setor Palotina](https://www.dropbox.com/s/7vwzkdd5okqd55t/2013%20DIAS%20et%20al.%20-%20RBB%20v9.pdf?dl=0)

Revista da Sociedade Brasileira de Bioética, V. 9, p. 298

Florianópolis, SC, Brazil

2013

Dias NA, Cestari FK and <u>**Favalesso MM**</u>

### [Divergência na decomposição de carcaça de *Sus scrofa* L. em experimentos de Entomologia Forense](https://www.szu.org.uy/assets/boletin/libro_resumenes_iicuz.pdf)

Anais del II Congreso Uruguayo de Zoología, v. 2, p. 147

Montevideo, Uruguay

2012

Chiarini R, Cestari FK and <u>**Favalesso MM**</u>

### [Estudo preliminar da fauna cadavérica no município de Palotina, Paraná - Sucessão entomológica](http://www.siepe.ufpr.br/2012/adocs/livro_siepe.pdf)

20º Evinci e 5º Einti

Palotina, PR, Brazil

2012

<u>**Favalesso MM**</u>, Cestari FK, Lima N and Tostes R

### [Avaliação da retenção de conteúdos teóricos em alunos submetidos às atividades práticas](https://www.dropbox.com/s/7aqh1bl0je9pfrm/2012%20OLIVEIRA%20et%20al.%20-%20XXI%20Semana%20academica%20de%20bio%20UNIOESTE.pdf?dl=0)

XXI Semana Acadêmica de Biologia da UNIOESTE

Cascavel, PR, Brazil

2012

Oliveira JB, Vendrame C, <u>**Favalesso MM**</u>, Peireira-Júnior M, Lucyk N, Artmann N, Aranha JM and Guimarães ATB


