---
title: "Introdução a modelagem de distribuição de espécies com exemplo no R"
description: |
  Curso ministrado no evento "Dados da Ecologia e Meio Ambiente Aplicados ao R"
author:
  - name: Marília Melo Favalesso
    url: www.mmfava.com
categories: 
  - R-ladies
  - R
  - Modelagem de distribuição de espécies
  - Modelagem de nicho ecológico
  - ENMTML
date: 10-31-2020
output:
  distill::distill_article:
    self_contained: false
---


A Modelagem de Distribuição de Espécies (SDM) visa relacionar ocorrências conhecidas de uma determinada espécie com variáveis ambientais preditoras que, combinadas para formar modelos estatísticos teóricos, possibilitam encontrar novas áreas adequadas para a ocorrência dessa espécie no espaço geográfico.  Nesse curso introdutório, falei sobre os princípios básicos da SDM, quais são os dados utilizados na calibração e avaliação de modelos, quais algoritmos são comumente utilizados, as aplicações dessa abordagem na área da ecologia e um exemplo de aplicação no R. Os seguintes tópicos foram abordados: Introdução aos Modelos de Distribuição de Espécies; Aplicações; Nicho Ecológico e Distribuição das Espécies; Construção e avaliação dos SDMs; exemplo no R.

[Aqui você acessa o link do evento.](https://www.sympla.com.br/we-r-ladies---dados-da-ecologia-e-meio-ambiente-aplicados-ao-r__1013350)

## Slides

```{r echo=FALSE}
knitr::include_url('niche_modelling.html')
```





